version: 0.0
os: linux
files:
  - source: target/rest-api-file-transfer-0.0.1-SNAPSHOT.jar
    destination: /app/lib/
  - source: config/application.yml
    destination: /app/config/
  - source: config/logback.xml
    destination: /app/config/
hooks:
  ApplicationStart:
    - location: scripts/start-app.sh
      timeout: 3600
      runas: root
  ApplicationStop:
    - location: scripts/stop-app.sh
      timeout: 3600
      runas: root